location = /rive-viewer {
    return 308 /rive-viewer/;
}

location = /rive-viewer/index.html {
    root /var/www/rive-viewer/current;
    expires -1;
}

location ^~ /rive-viewer/ {
    root /var/www/rive-viewer/current;
    try_files $uri $uri/ /rive-viewer/index.html;
    expires 7d;
}
